### ISSUE TITLE
Docker check fails on windows

### ISSUE THREAD

**Issue by madmartian5** [Zilliqa/ceres#6]
The docker check that is done to detect whether docker is running or not does not work on windows. 
A quick look, and the issue is that via socket.io - a connection to` /var/run/docker.sock` is being attmpted. However, on windows that is not an accessible path.

As such, no option is available to install the containers.

**Comment by madmartian5** [comment]
The issue is actually deeper than just the check.. the main issue is this line here:

`var docker = new Docker({ socketPath: "/var/run/docker.sock" });`

which will not work on windows.

**Comment by micovi** [comment]
Hi, thanks for your report. The problem is indeed deeper, with docker integration and not only the status checker. I am currently working on a fix for Windows. 

Also, I think there will be useful to have a settings panel that allows user to edit the docker socket path used by Ceres manually.

**Comment by madmartian5** [comment]
I think there are other node api libraries available that allow connecting via tcp - that may be an option?

**Comment by micovi** [comment]
The Docker library could be also instantiated using `new Docker({protocol:'tcp', host: '127.0.0.1', port: 2375});` options. I will do some tests on a Windows machine and see if it connects successfully.

**Comment by madmartian5** [comment]
I had changed that connnection.. but whilst no error - none of the calls were working. So, looks like it is more than just the quick fix unfortunately.
